# Generated by Django 5.0.6 on 2024-06-11 06:33

import bill.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('pan_no', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('image', models.ImageField(default='Image Not Found', null=True, upload_to='')),
                ('established', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bill.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_Type',
            field=models.ForeignKey(default='Select Company Type', on_delete=django.db.models.deletion.CASCADE, to='bill.company_types'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(default='', max_length=50)),
                ('Customer_phone', models.CharField(max_length=10)),
                ('Customer_Company', models.ForeignKey(default='company', on_delete=django.db.models.deletion.CASCADE, to='bill.company')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(default=0, max_length=10)),
                ('image', models.ImageField(default='', null=True, upload_to='')),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('Ordered_Item_Id', models.CharField(default=bill.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bill.product')),
            ],
        ),
    ]
