# Generated by Django 5.0.6 on 2024-06-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Customer_Company',
        ),
    ]
