# Generated by Django 5.0.6 on 2024-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
