# Generated by Django 5.0.6 on 2024-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_customer_address_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
