# Generated by Django 5.0.6 on 2024-06-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='modes_of_payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CQ', 'CHEQUE'), ('CD', 'CASH ON DELIVERY'), ('QR', 'QR CODE'), ('ES', 'ESEWA')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
