# Generated by Django 5.0.6 on 2024-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_orders_discount_orders_modes_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
