# Generated by Django 5.0.6 on 2024-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_orders_options_alter_orders_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
