# Generated by Django 5.0.6 on 2024-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_alter_orders_discount_alter_orders_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
