# Generated by Django 5.0.6 on 2024-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_alter_orders_discount_alter_orders_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
