# Generated by Django 5.0.6 on 2024-06-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='modes_of_payment',
            field=models.CharField(default='', max_length=20),
        ),
    ]
