# Generated by Django 5.0.6 on 2024-06-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_alter_orders_modes_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_id',
            new_name='Invoice_No',
        ),
    ]
