# Generated by Django 5.0.6 on 2024-06-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_rename_order_id_orders_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='Invoice_no',
        ),
    ]
