# Generated by Django 5.0.6 on 2024-06-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_rename_order_id_orderitems_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='Invoice_no',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Invoice_No',
            new_name='Order_id',
        ),
    ]
