# Generated by Django 5.0.6 on 2024-06-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_rename_invoice_no_orderitems_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_id',
            new_name='Invoice_No',
        ),
    ]
