# Generated by Django 5.0.6 on 2024-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_rename_order_id_orderitems_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
