# Generated by Django 5.0.6 on 2024-06-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0020_remove_orders_discount_orderitems_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
