# Generated by Django 5.0.6 on 2024-06-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0021_remove_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='vat',
            field=models.IntegerField(default=0),
        ),
    ]
