# Generated by Django 5.0.6 on 2024-06-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_orders_total_orders_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
