# Generated by Django 5.0.6 on 2024-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0023_alter_orders_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='vat',
            field=models.IntegerField(default=0),
        ),
    ]
