# Generated by Django 5.0.6 on 2024-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0024_alter_orders_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Paid', max_length=10),
        ),
    ]
