# Generated by Django 5.0.6 on 2024-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
